dist: bionic
addons:
  apt:
    packages:
      - pkg-config
      - libsystemd-dev
      - libjsoncpp-dev
      - googletest
      - meson
      - g++-8

language: cpp

script:
  - meson build/
  - ninja -C build/
  - ninja -C build/ test

matrix:
  include:
    - compiler: gcc
      env:
        - CC="gcc-8" CXX="g++-8"

    - compiler: clang

    - env:
        - JOB_TYPE="clang-format"
      addons:
        apt:
          packages:
            - clang-format
      script:
        - ./oomd/clang-format.sh
        -  git diff --exit-code

notifications:
  irc:
    channels:
      - "chat.freenode.net#oomd"
    on_success: change
    on_failure: always
